version: '3.9'
services:
  # install web services (wait & depend on redis) - port 3000
  web:
    build: 
      context: .
      dockerfile: './docker/web/Dockerfile'
    container_name: 'commerce-web'
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    ports:
      - '3000:3000'
    volumes: # [!] Volumes bind share files, folders between filesystem - container
      - './:${DOCKER_WEB_WORKDIR}' # when change file in filesystem it auto update to container (Ex: nodemon restart server)
      - 'dependencies:${DOCKER_WEB_WORKDIR}/node_modules' # Run base on node_modules from container
    working_dir: '${DOCKER_WEB_WORKDIR}'
    links: 
      - 'redis'
      - 'mongo'
    depends_on:
      - 'redis'
      - 'mongo'
  # install redis - port 6379
  redis:
    image: 'redis:alpine'
    container_name: 'commerce-redis'
    hostname: 'redis' # Use to another container connect to this (Check in .env to see usage)
    command: ["redis-server"]
    ports:
      - '6379:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      retries: 3
      timeout: 5s
  # install mongodb - port 27017
  mongo:
    image: mongo:5.0.3-focal
    container_name: 'commerce-db'
    hostname: 'mongodb.local' # Use to another container connect to this (Check in .env to see usage)
    restart: always
    ports:
      - '${FORWARD_MONGO_PORT:-27017}:27017'
    healthcheck:
      test: ['CMD', 'mongo', '--version']
      retries: 3
      timeout: 5s
volumes:
  dependencies: 